config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'

  resources :consultations
  resources :medic_consultations
  devise_for :users
  resources :patients
  resources :medicines
  resources :diagnoses
  resources :events
  authenticated :user do
 	  root 'visitors#index'
  end

  unauthenticated :user do
   	root 'welcome#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :user

  #validates :patient_dni, :consult_code, presence:true
  #validates :patient_dni, numericality: { only_integer: true }, length: { in:100000..100000000}
  #validates :consult_code, numericality: { only_integer: true }, length: { in:100..100000}

  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
	validates :description, presence: true
	after_create :save_medicines

	has_many :diagnosis_medicines
	has_many :medicines, through: :diagnosis_medicines
	def medicines=(value)
		@medicines = value
	end

	def save_medicines
		@medicines.each do |medicine_id|
			DiagnosisMedicine.create(medicine_id: medicine_id,diagnosis_id: self.id)
		end
	end
end

app/models/diagnosis_medicine.rb
class DiagnosisMedicine < ApplicationRecord
  belongs_to :diagnosis
  belongs_to :medicine
  belongs_to :medic_consultation

  def self.all_for_consultation(diagnosis_id)
		DiagnosisMedicine.where(diagnosis_id: diagnosis_id)
	end

	def self.medicines_ids(diagnosis_id)
   medicines = DiagnosisMedicine.where(diagnosis_id: diagnosis_id)
   @medicines = []
   medicines.each do |medicine|
    puts medicine
    @medicines[@medicines.length] = medicine.medicine_id
   end
   return @medicines
  end
end

app/models/event.rb
class Event < ApplicationRecord
	validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/has_diagnosis.rb
class HasDiagnosis < ApplicationRecord
  belongs_to :medic_consultation
  belongs_to :diagnosis
end

app/models/has_medic_consultation.rb
class HasMedicConsultation < ApplicationRecord
  belongs_to :patient
  belongs_to :medic_consultation
end

app/models/medic_consultation.rb
class MedicConsultation < ApplicationRecord
  belongs_to :user
  after_create :save_consultation
  has_many :has_diagnoses
  has_many :diagnoses, through: :has_diagnoses
  
  has_many :diagnosis_medicines
  has_many :medicines, through: :diagnosis_medicines

  validates :dni, presence: true, numericality: { only_integer: true }, length: { in:0..100000000}
  def diagnoses=(value)
		@diagnoses = value
	end

	def save_consultation
		@diagnoses.each do |diagnosis_id|
			HasDiagnosis.create(medic_consultation_id: self.id,diagnosis_id: diagnosis_id)
		end
	end
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	validates :name, :description, :stock, presence: true
	validates :stock, numericality: { only_integer: true }
	validates :stock, length: { minimum: 0 }
	validates :name, length: { in: 1..100}
	def self.mostrar(medicine_id)
		Medicine.where(id: medicine_id)
	end
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :has_medic_consultations
	has_many :medic_consultations, through: :has_medic_consultations
	#has_many :consultations
	validates :dni, :name, :last_name, :birthday, :age,:sex, presence: true
	validates :dni,:age, numericality: { only_integer: true }
	validates :age, length: { in: 1..120}
	validates :dni, length: { in: 8..10 }
	validates :name, :last_name, length: { in: 1..20}
	validates :sex, inclusion: {in: ["F","M"]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :medic_consultations
  has_many :consultations
  
  validates :name, :last_name, :birthday,:genre, presence: true
  validates :name, :last_name, length: {in: 1..20}
  validates :genre, inclusion: {in:  ["F","M"]}

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  def home
  end

  def set_layout
  	"application"
  end

end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def set_layout
    "application"
  end
  
  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.order('name ASC')
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:name, :description, :stock, :dosis, :observations)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def set_layout
  	return "landing" if action_name == "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/medicines/_form.html.erb
<%= simple_form_for @medicine, local: true, input_html:{ class: "form top-space"} do |form| %>
    <div class="contenedor-inputs top-space">
      <div class="field medium ">
        <div class=""><%= form.input :name, id: :medicine_name, input_html:{class: 'input-medicine'} %></div>
      </div>

      <div class="field medium">
        <%= form.label :stock %>
        <div class=""> <%= form.input_field :stock, id: :medicine_stock, min: 0, class: 'input-medicine form-control' %></div>
      </div>

      <div class="field medium">
        <div class=""><%= form.input :description, id: :medicine_description, input_html:{class: 'text-medicine'} %></div>
      </div>

      <div class="field medium">
        <div class=""> <%= form.input :dosis, id: :medicine_dosis, input_html:{class: 'text-medicine'} %></div>
      </div>

      <div class="field medium">
        <div class=""> <%= form.input :observations, id: :medicine_observations, input_html:{class: 'text-medicine'} %></div>
      </div>
      <div class="form-actions btn-medicine" style="width: 100%;">
        <%= form.button :submit %>
        <%= link_to 'Back', medicines_path, class: 'btn' %>

      </div>
    </div>

    
<% end %>

app/views/medicines/edit.html.erb
<h1 class="contenedor-inputs" style="margin-top: 0%; margin-bottom: 5%;">Editing Medicine</h1>

<%= render 'form', medicine: @medicine %>
<div class="form medium">
	<%= link_to 'Show', @medicine, class: 'btn btn-info',style: "margin-left:15px;margin-top:5px;" %> 
	<!--<%= link_to 'Back', medicines_path %>-->
</div>

app/views/medicines/index.html.erb
<h1 class="contenedor-inputs" style="margin-top: 0%; margin-bottom: 2%;">Medicines</h1>
<div style=" margin: auto; margin-bottom: 10px;" class="medium"><%= link_to 'New Medicine', new_medicine_path, class: "btn" %></div>
<div style="overflow-x: auto; ">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Dosis</th>
      <th>Observations</th>
      <th>Stock</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicines.each do |medicine| %>
      <tr>
        <td><%= medicine.name %></td>
        <td><%= medicine.description %></td>
        <td><%= medicine.dosis %></td>
        <td><%= medicine.observations %></td>
        <td><%= medicine.stock %></td>
        <td><%= link_to 'Show', medicine %></td>
        <td><%= link_to 'Edit', edit_medicine_path(medicine) %></td>
        <td><%= link_to 'Destroy', medicine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/medicines/new.html.erb
<h1 class="contenedor-inputs" style="margin-top: 0%; margin-bottom: 3%;">New Medicine</h1>

<%= render 'form', medicine: @medicine %>

<!-- <div class="form contenedor-inputs" style="background-color: #eee"><%= link_to 'Back', medicines_path %></div> -->

app/views/medicines/show.html.erb
<h1 class="contenedor-inputs" style="margin-top: 0%; margin-bottom: 5%;">Information</h1>
<div class="top-space">
  <div class="row middle-xs center-xs full-height no-margin top-space">
    <%= grid class:"row center-xs" do %>
      <div class="big-padding white contenedor-info">
        <p class="medium">
          <i class="fas fa-asterisk"></i>
          <strong>Name:</strong>
          <%= @medicine.name %>
        </p>

        <p class="medium">
          <i class="fas fa-asterisk"></i>
          <strong>Description:</strong>
          <%= @medicine.description %>
        </p>

        <p class="medium">
          <i class="fas fa-asterisk"></i>
          <strong>Dosis:</strong>
          <%= @medicine.dosis %>
        </p>

        <p class="medium">
          <i class="fas fa-asterisk"></i>
          <strong>Observations:</strong>
          <%= @medicine.observations %>
        </p>

        <p class="medium">
          <i class="fas fa-asterisk"></i>
          <strong>Stock:</strong>
          <%= @medicine.stock %>
        </p>
        <%= link_to 'Edit', edit_medicine_path(@medicine) %> |
        <%= link_to 'Back', medicines_path %>
      </div>
    <% end %>
  </div>
</div>