config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'

  resources :consultations
  resources :medic_consultations
  devise_for :users
  resources :patients
  resources :medicines
  resources :diagnoses
  resources :events
  authenticated :user do
 	  root 'visitors#index'
  end

  unauthenticated :user do
   	root 'welcome#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :user

  #validates :patient_dni, :consult_code, presence:true
  #validates :patient_dni, numericality: { only_integer: true }, length: { in:100000..100000000}
  #validates :consult_code, numericality: { only_integer: true }, length: { in:100..100000}

  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
	validates :description, presence: true
	after_create :save_medicines

	has_many :diagnosis_medicines
	has_many :medicines, through: :diagnosis_medicines
	def medicines=(value)
		@medicines = value
	end

	def save_medicines
		@medicines.each do |medicine_id|
			DiagnosisMedicine.create(medicine_id: medicine_id,diagnosis_id: self.id)
		end
	end
end

app/models/diagnosis_medicine.rb
class DiagnosisMedicine < ApplicationRecord
  belongs_to :diagnosis
  belongs_to :medicine
  belongs_to :medic_consultation

  def self.all_for_consultation(diagnosis_id)
		DiagnosisMedicine.where(diagnosis_id: diagnosis_id)
	end

	def self.medicines_ids(diagnosis_id)
   medicines = DiagnosisMedicine.where(diagnosis_id: diagnosis_id)
   @medicines = []
   medicines.each do |medicine|
    puts medicine
    @medicines[@medicines.length] = medicine.medicine_id
   end
   return @medicines
  end
end

app/models/event.rb
class Event < ApplicationRecord
	validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/has_diagnosis.rb
class HasDiagnosis < ApplicationRecord
  belongs_to :medic_consultation
  belongs_to :diagnosis
end

app/models/has_medic_consultation.rb
class HasMedicConsultation < ApplicationRecord
  belongs_to :patient
  belongs_to :medic_consultation
end

app/models/medic_consultation.rb
class MedicConsultation < ApplicationRecord
  belongs_to :user
  after_create :save_consultation
  has_many :has_diagnoses
  has_many :diagnoses, through: :has_diagnoses
  
  has_many :diagnosis_medicines
  has_many :medicines, through: :diagnosis_medicines

  validates :dni, presence: true, numericality: { only_integer: true }, length: { in:0..100000000}
  def diagnoses=(value)
		@diagnoses = value
	end

	def save_consultation
		@diagnoses.each do |diagnosis_id|
			HasDiagnosis.create(medic_consultation_id: self.id,diagnosis_id: diagnosis_id)
		end
	end
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	validates :name, :description, :stock, presence: true
	validates :stock, numericality: { only_integer: true }
	validates :stock, length: { minimum: 0 }
	validates :name, length: { in: 1..100}
	def self.mostrar(medicine_id)
		Medicine.where(id: medicine_id)
	end
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :has_medic_consultations
	has_many :medic_consultations, through: :has_medic_consultations
	#has_many :consultations
	validates :dni, :name, :last_name, :birthday, :age,:sex, presence: true
	validates :dni,:age, numericality: { only_integer: true }
	validates :age, length: { in: 1..120}
	validates :dni, length: { in: 8..10 }
	validates :name, :last_name, length: { in: 1..20}
	validates :sex, inclusion: {in: ["F","M"]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :medic_consultations
  has_many :consultations
  
  validates :name, :last_name, :birthday,:genre, presence: true
  validates :name, :last_name, length: {in: 1..20}
  validates :genre, inclusion: {in:  ["F","M"]}

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  def home
  end

  def set_layout
  	"application"
  end

end

app/controllers/medic_consultations_controller.rb
class MedicConsultationsController < ApplicationController
  before_action :set_medic_consultation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def set_layout
    "application"
  end
  # GET /medic_consultations
  # GET /medic_consultations.json
  def index
    @medic_consultations = MedicConsultation.all
    
  end
  def complete

  end
  # GET /medic_consultations/1
  # GET /medic_consultations/1.json
  def show
    @diagnosis_medicines = DiagnosisMedicine.all_for_consultation(@medic_consultation.diagnoses)
    @diagnosis_id = DiagnosisMedicine.medicines_ids(@medic_consultation.diagnoses) 
    @medicines = Medicine.mostrar(@diagnosis_id)
  end

  # GET /medic_consultations/new
  def new
    @diagnoses = Diagnosis.all
    @medic_consultation = MedicConsultation.new
    #@medicines = Medicine.where()
  end

  # GET /medic_consultations/1/edit
  def edit
    @diagnoses = Diagnosis.all
  end

  # POST /medic_consultations
  # POST /medic_consultations.json
  def create
    @consulta = false
    @dni = params[:dni]
    @patients = Patient.where(dni: @dni)
    if @patients.present?
      @medic_consultation = current_user.medic_consultations.new(medic_consultation_params)
      @medic_consultation.diagnoses = params[:diagnoses]
      respond_to do |format|
        
        if @medic_consultation.save
          format.html { redirect_to @medic_consultation, notice: 'Medic consultation was successfully created.' }
          format.json { render :show, status: :created, location: @medic_consultation }
        else
          format.html { render :new }
          format.json { render json: @medic_consultation.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_patient_path, notice: 'Patient does not exist.'
      @consulta = true
    end
    

  end

  # PATCH/PUT /medic_consultations/1
  # PATCH/PUT /medic_consultations/1.json
  def update
    respond_to do |format|
      if @medic_consultation.update(medic_consultation_params)
        format.html { redirect_to @medic_consultation, notice: 'Medic consultation was successfully updated.' }
        format.json { render :show, status: :ok, location: @medic_consultation }
      else
        format.html { render :edit }
        format.json { render json: @medic_consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medic_consultations/1
  # DELETE /medic_consultations/1.json
  def destroy
    @medic_consultation.destroy
    respond_to do |format|
      format.html { redirect_to medic_consultations_url, notice: 'Medic consultation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medic_consultation
      @medic_consultation = MedicConsultation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medic_consultation_params
      params.permit(:dni, :diagnoses)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/medic_consultations_helper.rb
module MedicConsultationsHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/medic_consultations/_form.html.erb
<%= form_with(model: @medic_consultation, local: true, class: "form-diagnosis") do |f| %>
  <div class="contenedor-consult">
    <div class="field medium">
      <label>DNI</label>
      <div style="width: 100%;"><%= number_field_tag :dni, params[:dni], in:0..100000000,class: "form-control" %></div>
    </div>
    <div class="field medium">
      <label>Diagnoses</label>
      <%= select_tag "diagnoses[]", options_from_collection_for_select(@diagnoses,"id","description"), class: "js-example-basic-multiple form-control input-diagnosis ",id: 'select1', multiple: "", presence: true %>
    </div>
    
    <div class="form-actions btn-consult">
      <%= f.submit 'Save',class: "btn" %>
      <%= link_to 'Back', medic_consultations_path, class: 'btn' %>
    </div>
  </div>

<% content_for :js do %>
<script type="text/javascript">
  $(document).ready(function() {

    $('.js-example-basic-multiple').select2({
      width: 'resolve',
      placeholder: "Select one or more diagnoses"
    });
  });

</script>
<% end %>
<% end %>

app/views/medic_consultations/complete.html.erb
<%= form_with(model: @medic_consultation) do |form| %>
	<h2>Medicines</h2>
	<div class="field">
    <%= f.label :medicine %>
    <% @medicines.each do |medicine| %>
    	<div><%= check_box_tag "medicines[]", medicine.id %><%= medicine.name %></div>
    <% end %>
  </div>
  <div class="actions">
  	<%= f.submit 'Accept' %>
  </div>
<% end %>

app/views/medic_consultations/edit.html.haml
%h1.contenedor-inputs{style:"margin-top:0%;margin-bottom:10%;"} Editing medic consultation

= render 'form'
%div.form-diagnosis.medium.top-space
	= link_to 'Show', @medic_consultation,class: "btn btn-info",style: "margin-top: 5px;margin-left:25px;"

app/views/medic_consultations/index.html.haml
%h1.contenedor-inputs{style:"margin-top: 0%; margin-bottom: 2%;"} Medic consultations
%div.btn.medium{style:"margin-bottom:20px;"}= link_to 'New Medic consultation', new_medic_consultation_path
%table{style:""}
  %thead
    %tr{style:"text-align:center;"}
      %th Patient's DNI
      / %th Diagnosis
      / %th Medicine
      %th Doctor
      %th
      %th
      %th

  %tbody
    - @medic_consultations.each do |medic_consultation|
      %tr{style:"text-align: center;"}
        %td= medic_consultation.dni
        / %td= medic_consultation.diagnosis
        / %td= medic_consultation.medicine
        %td= medic_consultation.user.name
        %td= link_to 'Show', medic_consultation
        %td= link_to 'Edit', edit_medic_consultation_path(medic_consultation)
        %td= link_to 'Destroy', medic_consultation, method: :delete, data: { confirm: 'Are you sure?' }

app/views/medic_consultations/new.html.haml
%h1.contenedor-inputs{style:"margin-top:0%;margin-bottom:10%;"} New medic consultation

= render 'form'

//%div.contenedor-inputs.form-diagnosis{style:"background-color:#eee;"}= link_to 'Back', medic_consultations_path

app/views/medic_consultations/show.html.haml
%h1.contenedor-inputs{style:"margin-top:0%;margin-bottom:5%;"} Information
.top-space
  .row.middle-xs.center-xs.full-height.no-margin.top-space
    =grid class:"row center-xs" do
      
      .big-padding.white.contenedor-info{style:""}
        %p.medium
          %b DNI:
          = @medic_consultation.dni
        %p.medium
          %b Diagnoses:
          - @medic_consultation.diagnoses.each do |diagnosis|
            %p.medium
              = diagnosis.description
        / %p
        /   %b Medicine id:
        /   - @diagnosis_medicines.each do |medicine|
        /     %p
        /       = medicine.medicine_id
        %p.medium
          %b Medicines available:
          - @medicines.each do |medicine|
            %p.medium
              = medicine.name
        %p.medium
          %b Doctor:
          = @medic_consultation.user.name
          = @medic_consultation.user.last_name

        = link_to 'Edit', edit_medic_consultation_path(@medic_consultation)
        \|
        = link_to 'Back', medic_consultations_path