config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'

  resources :consultations
  resources :medic_consultations
  devise_for :users
  resources :patients
  resources :medicines
  resources :diagnoses
  resources :events
  authenticated :user do
 	  root 'visitors#index'
  end

  unauthenticated :user do
   	root 'welcome#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :user

  #validates :patient_dni, :consult_code, presence:true
  #validates :patient_dni, numericality: { only_integer: true }, length: { in:100000..100000000}
  #validates :consult_code, numericality: { only_integer: true }, length: { in:100..100000}

  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
	validates :description, presence: true
	after_create :save_medicines

	has_many :diagnosis_medicines
	has_many :medicines, through: :diagnosis_medicines
	def medicines=(value)
		@medicines = value
	end

	def save_medicines
		@medicines.each do |medicine_id|
			DiagnosisMedicine.create(medicine_id: medicine_id,diagnosis_id: self.id)
		end
	end
end

app/models/diagnosis_medicine.rb
class DiagnosisMedicine < ApplicationRecord
  belongs_to :diagnosis
  belongs_to :medicine
  belongs_to :medic_consultation

  def self.all_for_consultation(diagnosis_id)
		DiagnosisMedicine.where(diagnosis_id: diagnosis_id)
	end

	def self.medicines_ids(diagnosis_id)
   medicines = DiagnosisMedicine.where(diagnosis_id: diagnosis_id)
   @medicines = []
   medicines.each do |medicine|
    puts medicine
    @medicines[@medicines.length] = medicine.medicine_id
   end
   return @medicines
  end
end

app/models/event.rb
class Event < ApplicationRecord
	validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/has_diagnosis.rb
class HasDiagnosis < ApplicationRecord
  belongs_to :medic_consultation
  belongs_to :diagnosis
end

app/models/has_medic_consultation.rb
class HasMedicConsultation < ApplicationRecord
  belongs_to :patient
  belongs_to :medic_consultation
end

app/models/medic_consultation.rb
class MedicConsultation < ApplicationRecord
  belongs_to :user
  after_create :save_consultation
  has_many :has_diagnoses
  has_many :diagnoses, through: :has_diagnoses
  
  has_many :diagnosis_medicines
  has_many :medicines, through: :diagnosis_medicines

  validates :dni, presence: true, numericality: { only_integer: true }, length: { in:0..100000000}
  def diagnoses=(value)
		@diagnoses = value
	end

	def save_consultation
		@diagnoses.each do |diagnosis_id|
			HasDiagnosis.create(medic_consultation_id: self.id,diagnosis_id: diagnosis_id)
		end
	end
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	validates :name, :description, :stock, presence: true
	validates :stock, numericality: { only_integer: true }
	validates :stock, length: { minimum: 0 }
	validates :name, length: { in: 1..100}
	def self.mostrar(medicine_id)
		Medicine.where(id: medicine_id)
	end
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :has_medic_consultations
	has_many :medic_consultations, through: :has_medic_consultations
	#has_many :consultations
	validates :dni, :name, :last_name, :birthday, :age,:sex, presence: true
	validates :dni,:age, numericality: { only_integer: true }
	validates :age, length: { in: 1..120}
	validates :dni, length: { in: 8..10 }
	validates :name, :last_name, length: { in: 1..20}
	validates :sex, inclusion: {in: ["F","M"]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :medic_consultations
  has_many :consultations
  
  validates :name, :last_name, :birthday,:genre, presence: true
  validates :name, :last_name, length: {in: 1..20}
  validates :genre, inclusion: {in:  ["F","M"]}

end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  before_action :set_consultation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def set_layout
    "application"
  end
  # GET /consultations
  # GET /consultations.json
  def index
    @consultations = Consultation.where(start: params[:start]..params[:end])
  end

  # GET /consultations/1
  # GET /consultations/1.json
  def show
  end

  # GET /consultations/new
  def new
    @consultation = Consultation.new
  end

  # GET /consultations/1/edit
  def edit

  end

  # POST /consultations
  # POST /consultations.json
  def create
    @patient_dni = params[:patient_dni]
    @patients = Patient.where(dni: @patient_dni)
    if @patients.present?
      @consultation = current_user.consultations.new(consultation_params)
      respond_to do |format|
        if @consultation.save
          format.html { redirect_to @consultation, notice: 'Consultation was successfully created.' }
          format.json { render :show, status: :created, location: @consultation }
        else
          format.html { render :new }
          format.json { render json: @consultation.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_patient_path, notice: 'Patient does not exist.'
    end
  end

  # PATCH/PUT /consultations/1
  # PATCH/PUT /consultations/1.json
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to @consultation, notice: 'Consultation was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultation }
      else
        format.html { render :edit }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultations/1
  # DELETE /consultations/1.json
  def destroy
    @consultation.destroy
    respond_to do |format|
      format.html { redirect_to consultations_url, notice: 'Consultation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultation
      @consultation = Consultation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultation_params
      params.permit(:patient_dni, :consult_code, :date_range, :start, :end)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  def home
  end

  def set_layout
  	"application"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def set_layout
  	return "landing" if action_name == "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/consultations/_edit.html.erb
<div class="modal fade" id="edit_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Edit Event</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @consultation %>
      </div>
    </div>
  </div>
</div>

app/views/consultations/_form.html.erb
<%= form_with(model: @consultation,local:true, class: "form-reservation",remote: true) do |f| %>
  <% if @consultation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@consultation.errors.count, "error")} prohibited this consultation from being saved:" %>
      </h2>
      <ul>
        <% @consultation.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="contenedor-reservations">
    <div class="field medium">
      <%= f.label :patient_dni %>
      <div>
        <%= number_field_tag :patient_dni, params[:patient_dni], in:100000..100000000, style:"width:90%;" %>
      </div>
    </div>
    <div class="field medium">
      <%= f.label :consult_code %>
      <div>
        <%= f.number_field :consult_code, in:100..100000,style:"width:90%" %>
      </div>
    </div>
    <div>
      <%= f.text_field :date_range, input_html: { class: "form-control input-sm date-range-picker"} %>
      <%= f.text_field :start, as: :hidden, value: Date.today, class: 'form-control input-sm start_hidden' %>
      <%= f.text_field :end, as: :hidden, value: Date.today, class: 'form-control input-sm end_hidden' %>
    </div>
    <div class="actions btn-consult">
      <%= f.submit 'Save' %>
      <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?'}, remote: true unless @consultation.new_record? %>
    </div>
  </div>
<% end %>

app/views/consultations/_new.html.erb
<div class="modal fade" id="new_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Create New Event</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @consultation %>
      </div>
    </div>
  </div>
</div>

app/views/consultations/create.js.erb
$('.calendar').fullCalendar(
	'renderConsultation',
	$.parseJSON("<%=j render(@consultation,format: :json).html_safe %>"),
	true
);
$('.modal').modal('hide');

app/views/consultations/destroy.js.erb
$('.calendar').fullCalendar('removeConsultations', [<%= @consultation.id %>])
$('.modal').modal('hide');

app/views/consultations/edit.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_event').modal('show');

app/views/consultations/index.html.haml
%h1.contenedor-inputs{style:"margin-top:0%;margin-bottom:2%;"} Listing consultations
%div.medium{style:"width:95%;margin:auto;margin-bottom:20px;"}= link_to 'New Consultation', new_consultation_path
%table
  %thead
    %tr
      %th Patient DNI
      %th Consult code
      %th Doctor
      %th
      %th
      %th

  %tbody
    - @consultations.each do |consultation|
      %tr{style:"text-align:center;"}
        %td= consultation.patient_dni
        %td= consultation.consult_code
        %td= consultation.user.name
        %td= link_to 'Show', consultation
        %td= link_to 'Edit', edit_consultation_path(consultation), remote: true
        %td= link_to 'Destroy', consultation, method: :delete, data: { confirm: 'Are you sure?' }

app/views/consultations/new.js.erb
$('#remote_container').html('<%= j render "new" %>');
$('#new_event').modal("show");

app/views/consultations/show.html.haml
%h1.contenedor-inputs{style:"margin-top:0%;margin-bottom:5%;"} Information
.top-space
	.row.middle-xs.center-xs.full-height.no-margin.top-space
		=grid class:"row center-xs" do
      
			.big-padding.white.contenedor-info{style:""}
				%p.medium
					%b Patient dni:
					= @consultation.patient_dni
				%p.medium
					%b Consult code:
					= @consultation.consult_code
				%p.medium
					%b Doctor:
					= @consultation.user.name
					= @consultation.user.last_name

				= link_to 'Edit', edit_consultation_path(@consultation)
				\|
				= link_to 'Back', consultations_path

app/views/consultations/update.js.erb
$('.calendar').fullCalendar('removeConsultations', [<%= @consultation.id %>]);
$('.calendar').fullCalendar(
	'renderConsultation',
	$.parseJSON("<%=j render(@consultation,format: :json).html_safe %>"),
	true
);
$('.modal').modal('hide');