config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'

  resources :consultations
  resources :medic_consultations
  devise_for :users
  resources :patients
  resources :medicines
  resources :diagnoses
  resources :events
  authenticated :user do
 	  root 'visitors#index'
  end

  unauthenticated :user do
   	root 'welcome#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :user

  #validates :patient_dni, :consult_code, presence:true
  #validates :patient_dni, numericality: { only_integer: true }, length: { in:100000..100000000}
  #validates :consult_code, numericality: { only_integer: true }, length: { in:100..100000}

  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
	validates :description, presence: true
	after_create :save_medicines

	has_many :diagnosis_medicines
	has_many :medicines, through: :diagnosis_medicines
	def medicines=(value)
		@medicines = value
	end

	def save_medicines
		@medicines.each do |medicine_id|
			DiagnosisMedicine.create(medicine_id: medicine_id,diagnosis_id: self.id)
		end
	end
end

app/models/diagnosis_medicine.rb
class DiagnosisMedicine < ApplicationRecord
  belongs_to :diagnosis
  belongs_to :medicine
  belongs_to :medic_consultation

  def self.all_for_consultation(diagnosis_id)
		DiagnosisMedicine.where(diagnosis_id: diagnosis_id)
	end

	def self.medicines_ids(diagnosis_id)
   medicines = DiagnosisMedicine.where(diagnosis_id: diagnosis_id)
   @medicines = []
   medicines.each do |medicine|
    puts medicine
    @medicines[@medicines.length] = medicine.medicine_id
   end
   return @medicines
  end
end

app/models/event.rb
class Event < ApplicationRecord
	validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/has_diagnosis.rb
class HasDiagnosis < ApplicationRecord
  belongs_to :medic_consultation
  belongs_to :diagnosis
end

app/models/medic_consultation.rb
class MedicConsultation < ApplicationRecord
  belongs_to :user
  after_create :save_consultation
  has_many :has_diagnoses
  has_many :diagnoses, through: :has_diagnoses
  
  has_many :diagnosis_medicines
  has_many :medicines, through: :diagnosis_medicines

  validates :dni, presence: true, numericality: { only_integer: true }, length: { in:0..100000000}
  def diagnoses=(value)
		@diagnoses = value
	end

	def save_consultation
		@diagnoses.each do |diagnosis_id|
			HasDiagnosis.create(medic_consultation_id: self.id,diagnosis_id: diagnosis_id)
		end
	end
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	validates :name, :description, :stock, presence: true
	validates :stock, numericality: { only_integer: true }
	validates :stock, length: { minimum: 0 }
	validates :name, length: { in: 1..100}
	def self.mostrar(medicine_id)
		Medicine.where(id: medicine_id)
	end
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :has_medic_consultations
	has_many :medic_consultations, through: :has_medic_consultations
	#has_many :consultations
	validates :dni, :name, :last_name, :birthday, :age,:sex, presence: true
	validates :dni,:age, numericality: { only_integer: true }
	validates :age, length: { in: 1..120}
	validates :dni, length: { in: 8..10 }
	validates :name, :last_name, length: { in: 1..20}
	validates :sex, inclusion: {in: ["F","M"]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :medic_consultations
  has_many :consultations
  
  validates :name, :last_name, :birthday,:genre, presence: true
  validates :name, :last_name, length: {in: 1..20}
  validates :genre, inclusion: {in:  ["F","M"]}

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  def home
  end

  def set_layout
  	"application"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HospitalApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="/mdl/material.min.css">
    <script src="/mdl/material.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="/web-fonts-with-css/css/fontawesome-all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
  		<%= render "partials/nav" %>
  		
  		<main role="main">
    		<div class="container">
          <%= render 'layouts/messages' %>
          <%= yield %>
          <div id="remote_container"></div>
        </div>
  		</main>
	 </div>
    
    <%= javascript_include_tag "application" %>
    <%= yield :js %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospitalApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="/mdl/material.min.css">
    <script src="/mdl/material.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="./app/assets/stylesheets/fontawesome-all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout">
  <header class="mdl-layout__header mdl-layout__header--scroll">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Hospital App</span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation -->
      <nav class="mdl-navigation">
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Hospital App</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="">Link</a>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <div class="page-content">
      <%= yield %>
    </div>
  </main>
</div>
    
  </body>
</html>

app/views/partials/_nav.html.erb
<header class='mdl-layout__header'>
  <div class='mdl-layout__header-row'>
    <div class='mdl-layout-spacer'></div>
    <div class='mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right'>
        <% if user_signed_in? %>
          <%= link_to "Cerrar sesión", destroy_user_session_path,method: :delete, class: "margin-left medium" %>
        <% end %>
      <label class='mdl-button mdl-js-button mdl-button--icon' for="fixed-header-drawer-exp">
        <i class='material-icons'>search</i>
      </label>
      <div class='mdl-textfield__expandable-holder'>
        <input class='mdl-textfield__input' type="text" name="sample" id="fixed-header-drawer-exp">
      </div>
    </div>
  </div>
</header>
<div class='mdl-layout__drawer'>
  <span class='mdl-layout-title'><%= link_to "HospitalApp", root_path,style:"text-decoration:none;" %></span>
  <% if user_signed_in? %>
    <label class="current_user">
      <i class="far fa-envelope" style="margin-right: 2px;"></i>
      <%=current_user.email%>
    </label>
  <% end %>
  <nav class='mdl-navigation'>

    <div class='mdl-navigation__link link'>
      <i class="fas fa-clipboard-list" style="margin-left: -15px;"></i>
      <%=link_to "Medic Consultations", medic_consultations_path, style:"text-decoration:none; margin-left:5px;" %>
      </div>
    <div class='mdl-navigation__link link'>
      <i class="fas fa-eye-dropper" style="margin-left: -15px;"></i>
      <%=link_to "Medicines", medicines_path, style:"text-decoration:none; margin-left:5px;" %>
    </div>
    <div class='mdl-navigation__link link'>
      <i class="fas fa-first-aid" style="margin-left: -15px;"></i>
      <%=link_to "Diagnoses", diagnoses_path, style:"text-decoration:none; margin-left:5px;" %>
    </div>
    <div class='mdl-navigation__link link'>
      <i class="fas fa-wheelchair" style="margin-left: -15px;"></i>
      <%=link_to "Patients", patients_path, style:"text-decoration:none; margin-left:5px;" %>
    </div>
  </nav>
</div>